providers = []
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1711411379'

[variables]
NIXPACKS_METADATA = 'python'
NIXPACKS_POETRY_VERSION = '1.3.1'
PYTHONUNBUFFERED = '1'
[phases.install]
dependsOn = ['setup']
cmds = [
    'python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install .',
]
cacheDirectories = ['/root/.cache/pip']
paths = ['/opt/venv/bin']

[phases.setup]
nixPkgs = ['python311', 'gcc']
nixLibs = ['zlib', 'stdenv.cc.cc.lib']
nixOverlays = []
nixpkgsArchive = '5148520bfab61f99fd25fb9ff7bfbb50dad3c9db'

[start]
cmd = 'python main.py'
